#!/usr/bin/env bash
sudo cp pretty_json.py /usr/bin/
sudo ln -s /usr/bin/pretty_json.py /usr/bin/pretty # Symbolic link to binary file

if [ "$?" -gt 0 ]
then
    echo "Success!"
else
    echo "Something not right!"
fi
